embeddings-model:
  name: "nvidia/llama-nemotron-embed-vl-1b-v2:free"

llm-model:
  name: "openrouter/owl-alpha"

reranker-model:
  name: "rerank-v3.5"

vision-model:
  name: "google/gemini-2.0-flash-001"